_config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import views as sitemaps_views
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

from home.sitemaps import HomeSitemap

apps_sitemap = {
    'home': HomeSitemap,
}

urlpatterns = [
    ## Django.
    path('admin/', admin.site.urls),
    path(route='accounts/', view=include('django.contrib.auth.urls')),
    ## I18n.
    path(route='i18n/', view=include('django.conf.urls.i18n')),
    path(
        route='jsi18n/',
        view=JavaScriptCatalog.as_view(),
        name='javascript-catalog',
    ),
    path(
        route='sitemap.xml',
        view=sitemaps_views.index,
        kwargs={'sitemaps': apps_sitemap},
        name='django.contrib.sitemaps.views.index',
    ),
    path(
        route='sitemap-<section>.xml',
        view=sitemaps_views.sitemap,
        kwargs={'sitemaps': apps_sitemap},
        name='django.contrib.sitemaps.views.sitemap',
    ),
    ## Apps.
    path(route='', view=include('home.urls')),
    path(route='accounts/', view=include('accounts.urls')),
]

## Rosetta.
## http://127.0.0.1:8000/rosetta/
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns.append(path(route='rosetta/', view=include('rosetta.urls')))

if settings.DEBUG:
    ## Static files (dev).
    urlpatterns += static(
        prefix=settings.STATIC_URL,
        document_root=settings.STATIC_ROOT,
    )
    urlpatterns += static(
        prefix=settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    ## Django debug toolbar.
    if not settings.TESTING:
        import debug_toolbar

        urlpatterns.append(
            path(route='__debug__/', view=include(debug_toolbar.urls)),
        )

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path(route='profile/', view=views.profile, name='profile'),
    path(route='signup/', view=views.SignUpView.as_view(), name='signup'),
    path(
        route='<int:pk>/<str:username>/update/',
        view=views.update,
        name='update',
    ),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path(route='', view=views.home, name='home'),
]

accounts/models.py
# Create your models here.

base/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class BaseModel(models.Model):
    active = models.BooleanField(
        verbose_name=_('active'),
        default=True,
        help_text=_('enables or disables the item.'),
    )
    created_at = models.DateTimeField(
        verbose_name=_('created at'),
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        verbose_name=_('updated at'),
        auto_now=True,
    )

    class Meta:
        abstract = True

home/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model


class UserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email')

accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic

from . import forms


def profile(request):
    return render(request, template_name='accounts/profile.html')


@login_required
def update(request, pk, username):
    form = forms.UserForm(
        data=request.POST or None,
        instance=get_object_or_404(get_user_model(), pk=pk, username=username),
    )
    if request.method == 'POST':
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('accounts:profile'))
    return render(
        request=request,
        template_name='accounts/update.html',
        context={'form': form, 'title': 'Atualizar'},
    )


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

base/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render
from django.utils.translation import gettext as _
from django.views.decorators.http import require_GET


@require_GET
def home(request):
    return render(
        request=request,
        template_name='home/home.html',
        context={'title': _('Hello World!')},
    )

accounts/templates/accounts/profile.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{{ get_user }}{% endblock %}
{% block keywords %}Profile{% endblock %}
{% block description %}Profile: {{ user.get_username }}.{% endblock %}
{% block content %}
{% translate "Not registered" as not_registered %}
{% with get_user=user.get_username %}
<div class="container">
    <div class="card mb-4">
        <div class="card-header">
            <b>{% translate "Name" %}</b>: {{ user.get_full_name|default:not_registered }}.
        </div>
        <div class="card-body">
            <p class="card-text"><b>{% translate "User" %}</b>: @{{ get_user }}.</p>
            <p class="card-text">
                <b>Email</b>: {{ user.email|default:not_registered }}.
            </p>
            <p class="card-text"><b>{% translate "Created in" %}</b>: {{ user.date_joined }}.</p>
            <a class="btn btn-primary me-4" href="{% url 'accounts:update' pk=user.pk username=get_user %}">
                {% translate "Update" %}
            </a>
            {% if user.is_superuser %}
            <a class="btn btn-warning" href="{% url 'admin:index' %}">
                Django admin
            </a>
            {% endif %}
        </div>
    </div>
</div>
{% endwith %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block title %}Create account{% endblock %}
{% block content %}
<div class="container">
    <h1>{% translate "Create account" %}</h1>
    {% include 'base/form.html' with button='Create' %}
</div>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block title %}{{ user.get_username }}{% endblock %}
{% block content %}
<div class="container">
    <h1>{% translate "Update account" %}</h1>
    {% include 'base/form.html' with button="Update" %}
</div>
{% endblock %}

base/templates/base/base.html
<!doctype html>{% load static %}
<html data-bs-theme="auto" lang="pt-BR">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="{% block author %}{% endblock %}" name="author">
    <meta content="{% block keywords %}{% endblock %}" name="keywords">
    <meta content="{% block description %}{% endblock %}" name="description">
    <link href="{% static 'base/favicons/favicon.png' %}" rel="apple-touch-icon" sizes="180x180">
    <link href="{% static 'base/favicons/favicon.png' %}" rel="icon" sizes="32x32" type="image/png">
    <link href="{% static 'base/favicons/favicon.png' %}" rel="icon" sizes="16x16" type="image/png">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}
    <link href="{% static 'base/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    {% endblock %}
</head>

<body>
{% include 'base/navbar.html' %}
{% include 'base/messages.html' %}
{% block content %}{% endblock %}
{% include 'base/footer.html' %}
{% block javascript %}
<script src="{% static 'base/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'base/js/bootstrap-change-theme-min.js' %}"></script>
{% endblock %}
</body>

</html>

base/templates/base/change-lang.html
{% load i18n %}
<form action="{% url 'set_language' %}" class="d-flex" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}"/>
    <select class="form-select form-select-sm" name="language">
        <option value="en-US">{% translate "Language" %}</option>
        <option value="en-US">{% translate "English" %}</option>
        <option value="pt-BR">{% translate "Portuguese (pt_BR)" %}</option>
    </select>
    <button class="btn btn-outline-secondary btn-sm" type="submit">{% translate "Change" %}</button>
</form>

base/templates/base/footer.html
<div class="container mt-5">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1" href="/">
                <svg class="bi" height="24" width="30">
                    <use xlink:href="#bootstrap"></use>
                </svg>
            </a>
            <span class="mb-3 mb-md-0 text-body-secondary">© 2024-{% now "Y" %} Renato Cruz, Inc</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-body-secondary" href="#">
                <i class="bi bi-twitter"></i>
            </a></li>
            <li class="ms-3"><a class="text-body-secondary" href="#">
                <i class="bi bi-instagram"></i>
            </a></li>
            <li class="ms-3"><a class="text-body-secondary" href="#">
                <i class="bi bi-facebook"></i>
            </a></li>
        </ul>
    </footer>
</div>

base/templates/base/form.html
{% load i18n %}
{% load django_bootstrap5 %}
<form action="." class="my-4" method="post">{% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary" type="submit">{% translate button %}</button>
</form>

base/templates/base/is-authenticated.html
{% load i18n %}
<ul class="navbar-nav">
    <li class="nav-item dropdown">
        <a aria-expanded="false" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button">
            {{ user.username }}
        </a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">{% translate "Profile" %}</a></li>
            {% if user.is_superuser %}
            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Django admin</a></li>
            {% endif %}
            <li>
                <hr class="dropdown-divider">
            </li>
            <form action="{% url 'admin:logout' %}" class="px-4 py-3" method="post">{% csrf_token %}
                <div class="d-grid gap-2 col-6 mx-auto">
                    <button class="btn btn-danger btn-sm" type="submit">{% translate "Exit" %}</button>
                </div>
            </form>
        </ul>
    </li>
</ul>

base/templates/base/messages.html
{% if messages %}
{% for message in messages %}
{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
<div class="alert alert-danger" role="alert">
    {{ message}}
</div>
{% else %}
<div class="alert alert-{{ message.tags }}" role="alert">
    {{ message}}
</div>
{% endif %}
{% endfor %}
{% endif %}

base/templates/base/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-5">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler"
                data-bs-target="#navbarSupportedContent" data-bs-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a aria-current="page" class="nav-link active" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a aria-expanded="false" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"
                       role="button">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a aria-disabled="true" class="nav-link disabled">Disabled</a>
                </li>
            </ul>
            <div class="d-flex me-5">
                {% if user.is_authenticated %}
                {% include 'base/is-authenticated.html' %}
                {% else %}
                <a class="btn btn-secondary me-1" href="{% url 'accounts:signup' %}" role="button">
                    {% translate "Sign up" %}
                </a>
                <a class="btn btn-success" href="{% url 'login' %}" role="button">{% translate "Log in" %}</a>
                {% endif %}
            </div>
            {% include 'base/change-lang.html' %}
        </div>
    </div>
</nav>

home/templates/home/home.html
{% extends 'base/base.html' %}]
{% load static %}
{% load i18n %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <p>{% translate "Welcome to the home page!" %}</p>
    <button class="btn btn-primary" id="homeButton" type="button ">
        {% translate "Click me" %}
    </button>
</div>
{% endblock %}
{% block javascript %}
{{ block.super }}
<script src="{% url 'javascript-catalog' %}"></script>
<script src="{% static 'home/js/main.js' %}"></script>
{% endblock %}